calibration:
 method: temperature_scaling
 n_bins: 15

 init_temperature: 1.0
 min_temperature: 0.05
 max_temperature: 10.0

 optimizer:
   name: lbfgs
   lr: 0.01
   max_iter: 100
   tolerance_grad: 1.0e-7
   tolerance_change: 1.0e-9
   line_search_fn: strong_wolfe

output:
 save_calibrated_predictions: true
